### PR TITLE
Move from Trollop to Optimist for CLI option passing

### PR DESCRIPTION
**Pull request by orien**
Trollop has been renamed to Optimist. Let's use the new name.

### CODE REVIEW

**Comment by morozgrafix** [comment]
I've submitted similar PR on this repo https://github.com/dougbarth/jsonlint/pull/1 wasn't sure which one is actually maintained. link from https://rubygems.org/gems/jsonlint took me there. Hope one of these is merged at some point in near future.

**Comment by Aeternitaas** [comment]
Thanks for your input, we've gone ahead and merged it in.

**Comment by olleolleolle** [comment]
@Aeternitaas Oh, thanks! I can't seem to find the merge here, has something changed?

**Comment by tscheffe** [comment]
Ran into this "error" today, would love to see some action on this PR!

**Comment by dougbarth** [comment]
Another PR moved the gem to optimist. Thanks for the effort!

**Pull request closed without merging**
